### Local request
GET http://localhost:5000/

### ddapi - get user by rank
GET http://localhost:5000/api/v2/ddapi/get_user_by_rank?rank=77
### ddapi - get user by id
GET http://localhost:5000/api/v2/ddapi/get_user_by_id?id=151675
### ddapi - get user by name
GET http://localhost:5000/api/v2/ddapi/get_user_by_name?name=VHS
### ddapi - get leaderboard scores
GET http://localhost:5000/api/v2/ddapi/get_scores?offset=1&limit=1

### get top games
GET http://localhost:5000/api/v2/game/top?limit=10
### get paginated list of most recent games
GET http://localhost:5000/api/v2/game/recent?playerid=229&pagesize=10&pagenum=1
### get game by game id
GET http://localhost:5000/api/v2/game?id=20
### get a list of all game states
GET http://localhost:5000/api/v2/game/all?id=20
### get a list of game states with game time and gems
GET http://localhost:5000/api/v2/game/gems?id=20
### get a list of game states with game time and homing daggers
GET http://localhost:5000/api/v2/game/homing_daggers?id=20
### get a list of game states with game time and daggers hit
GET http://localhost:5000/api/v2/game/daggers_hit?id=20
### get a list of game states with game time and daggers fired
GET http://localhost:5000/api/v2/game/daggers_fired?id=20
### get a list of game states with game time and accuracy
GET http://localhost:5000/api/v2/game/accuracy?id=20
### get a list of game states with game time and enemies alive
GET http://localhost:5000/api/v2/game/enemies_alive?id=20
### get a list of game states with game time and enemies killed
GET http://localhost:5000/api/v2/game/enemies_killed?id=20
###
GET http://localhost:5000/api/v2/player?id=230
###
GET http://localhost:5000/api/v2/player/update?id=230
###
GET http://localhost:5000/api/v2/player/all?pagesize=9&pagenum=1
### get message of the day
GET http://localhost:5000/api/v2/motd
### when client connects, this request responds with motd, valid_version, and update_available
POST http://localhost:5000/api/v2/client_connect
content-type: application/json

{
    "version": "0.4.5"
}
###
GET /happy HTTP/1.1
    Host: localhost:5000
    Connection: Upgrade
    Upgrade: websocket
    Origin: http://localhost:5000

###
GET http://localhost:5000/socket.io/ HTTP/1.1

###
GET /socket.io/?EIO=3&transport=polling&t=Mz-fjAm
    Host: localhost:5000
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0
    Accept: */*
    Accept-Language: en-US,en;q=0.5
    Accept-Encoding: gzip, deflate
    Origin: null
    Connection: keep-alive