### Local request
GET http://localhost:5000/

### ddapi - get user by rank
GET http://localhost:5000/api/v2/ddapi/get_user_by_rank?rank=1
### ddapi - get user by id
GET http://localhost:5000/api/v2/ddapi/get_user_by_id?id=148788