### ddapi - get user by rank
GET http://localhost:5000/api/v2/ddapi/get_user_by_rank?rank=3081
### ddapi - get user by id
GET http://localhost:5000/api/v2/ddapi/get_user_by_id?id=49457
### ddapi - get user by name
GET http://localhost:5000/api/v2/ddapi/get_user_by_name?name=VHS
### ddapi - get leaderboard scores
GET http://localhost:5000/api/v2/ddapi/get_scores?offset=400000&limit=100

### get top games
GET http://localhost:5000/api/v2/game/top?limit=10
### get paginated list of most recent games
GET http://localhost:5000/api/v2/game/recent?player_id=229&page_size=10&page_num=1
### get game by game id
GET http://localhost:5000/api/v2/game?id=67882
### get a list of all game states
GET http://localhost:5000/api/v2/game/full?id=20000
### get a list of all game states
GET http://localhost:5000/api/v2/game/all?id=20
### get a list of game states with game time and gems
GET http://localhost:5000/api/v2/game/gems?id=20
### get a list of game states with game time and homing daggers
GET http://localhost:5000/api/v2/game/homing_daggers?id=20
### get a list of game states with game time and daggers hit
GET http://localhost:5000/api/v2/game/daggers_hit?id=20
### get a list of game states with game time and daggers fired
GET http://localhost:5000/api/v2/game/daggers_fired?id=20
### get a list of game states with game time and accuracy
GET http://localhost:5000/api/v2/game/accuracy?id=20
### get a list of game states with game time and enemies alive
GET http://localhost:5000/api/v2/game/enemies_alive?id=20
### get a list of game states with game time and enemies killed
GET http://localhost:5000/api/v2/game/enemies_killed?id=20
###
GET http://localhost:5000/api/v2/player?id=229
###
GET http://localhost:5000/api/v2/player/update?id=230
###
GET http://localhost:5000/api/v2/player/all?page_size=9&page_num=1
###
GET http://localhost:5000/api/v2/player/live
### get message of the day
GET http://localhost:5000/api/get_motd
### get message of the day
GET http://localhost:5000/api/v2/motd
### get daily stats
GET http://localhost:5000/api/v2/daily
###
GET http://localhost:5000/api/v2/releases?page_size=10&page_num=1
###
GET http://localhost:5000/api/v2/news?page_size=10&page_num=1
### when client connects, this request responds with motd, valid_version, and update_available
POST http://localhost:5000/api/v2/client_connect
content-type: application/json

{
    "version": "0.4.5"
}